version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: match.log
    maxBytes: 1048576
    backupCount: 5
  summary:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: summary.log
    maxBytes: 1048576
    backupCount: 5
loggers:
  log_tests:
    level: DEBUG
    handlers: [console, file, summary]
    propagate: yes
root:
  level: DEBUG
  handlers: [console]
